name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main, master]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: pm-api-monitoring
  REGION: asia-southeast2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login ke Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      # Deploy ke Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --platform managed \
            --allow-unauthenticated \
            --memory=8Gi \
            --cpu=4 \
            --execution-environment=gen2 \
            --cpu-boost \
            --port 8080 \
            --timeout=600s \
            --no-cpu-throttling \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --set-env-vars "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" \
            --set-env-vars "ACCESS_TOKEN_AGE=${{ secrets.ACCESS_TOKEN_AGE }}" \
            --set-env-vars "API_PASSWORD=${{ secrets.API_PASSWORD }}" \
            --set-env-vars "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" \
            --set-env-vars "API_USERNAME=admin"
            
      - name: Log deployment URL
        run: |
          echo "ðŸš€ Backend deployment complete!"
          gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)'